AllCops:
  TargetRubyVersion: 2.0

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 30
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
